### ISSUE TITLE
cmd.js: Cannot find module 'baudio' from '.'

### ISSUE THREAD

**Issue by polybuildr** [substack/baudio#23]
After installing `npm -g baudio` to use `cmd.js` as a command line tool and then running
```
baudio test.js -d 4 -o test.wav
```
I get
```
/usr/lib/node_modules/baudio/bin/cmd.js:44
    var fn = vm.runInNewContext('(function(){'+src+'})()', ctx);
                ^
Error: Cannot find module 'baudio' from '.'
    at Function.module.exports [as sync] (/usr/lib/node_modules/baudio/node_modules/resolve/lib/sync.js:32:11)
    at ctx.require (/usr/lib/node_modules/baudio/bin/cmd.js:33:36)
    at evalmachine.<anonymous>:1:26
    at evalmachine.<anonymous>:129:3
    at fromSource (/usr/lib/node_modules/baudio/bin/cmd.js:44:17)
    at Object.<anonymous> (/usr/lib/node_modules/baudio/bin/cmd.js:26:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by dreaganluna** [comment]
same here

**Comment by flyswatter** [comment]
- Dan

**Comment by flyswatter** [comment]
Whoops for the empty comment. Not sure why you have that, was just reading it.
